"""Agent Host Protocol (AHP) - formally verified reducer core.

This package embeds the AHP channel reducers extracted from a Dafny
specification. The reducers, their convergence properties and the fold
laws over them are machine-checked proofs, not hand-written code.

The extracted modules are held in the private ``_core`` subpackage. They
are generated by Dafny with flat, absolute module names (``Chat``,
``Session``, ``_dafny``, ...) and import one another by bare name, so
``_core`` must be resolvable on ``sys.path`` while they load.

Import hygiene
--------------
Two things are done so that importing this package does not degrade the
importing process:

1. ``sys.path`` is modified only for the duration of the initial import
   and is restored afterwards, so no directory of this package is left
   on the global search path. Before this, ``_core`` was inserted at
   index 0 permanently, which outranks the standard library and
   site-packages for every subsequent import in the process.

2. Every extracted module is verified to have loaded from *this*
   package's ``_core`` directory. Because ``sys.modules`` is global and
   keyed by bare name, a second Dafny-extracted package in the same
   environment also provides ``_dafny``, ``module_`` and ``System_``.
   Whichever imports first wins. That collision is inherent to Dafny's
   Python backend and is not fixed here — but it is now *detected*, and
   raises ``ImportError`` naming the conflicting file rather than
   silently binding this package's reducers to a foreign runtime.

Channels
--------
root            Agent / session / terminal registry and client config.
session         Session lifecycle.
chat            Turn lifecycle and the tool-call state machine.
terminal        Terminal streams.
canvas          Canvas surface.
changeset       File changesets.
annotations     Source annotations.
resource_watch  Resource watching.

Each channel module exposes an ``ApplyTo<Channel>(state, action, now)``
reducer returning a ``(next_state, outcome)`` pair, alongside the
datatype constructors for its states and actions.

Example
-------
>>> from agent_host_protocol import root
>>> state = root.RootState_RootState(
...     agents, active_sessions, terminals, config)
>>> next_state, outcome = root.ApplyToRoot(state, action, now)
"""

from __future__ import annotations

import os as _os
import sys as _sys

_CORE_DIR = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "_core")

# The extracted modules import one another by bare name, so _CORE_DIR has to be
# resolvable while they load. It is inserted at index 0 (the extracted modules must
# win against any same-named module for the graph to load coherently) and removed
# again in the finally block, so the process-global search path is unchanged once
# this package has finished importing.
_sys.path.insert(0, _CORE_DIR)
try:
    import AhpSkeleton as _AhpSkeleton  # noqa: E402
    import Annotations as _Annotations  # noqa: E402
    import Canvas as _Canvas  # noqa: E402
    import Changeset as _Changeset  # noqa: E402
    import Chat as _Chat  # noqa: E402
    import ResourceWatch as _ResourceWatch  # noqa: E402
    import Session as _Session  # noqa: E402
    import Terminal as _Terminal  # noqa: E402
    import _dafny  # noqa: E402
finally:
    try:
        _sys.path.remove(_CORE_DIR)
    except ValueError:  # pragma: no cover - already removed by something else
        pass


def _assert_own_core(*modules: object) -> None:
    """Fail loudly if an extracted module came from a different package.

    ``sys.modules`` is keyed by bare name, so another Dafny-extracted
    distribution in the same environment can already own ``_dafny``,
    ``module_`` or ``System_``. Binding this package's proven reducers to a
    foreign runtime would be silent and arbitrarily wrong; this turns it into
    an explicit, diagnosable failure at import time.
    """
    core_prefix = _os.path.join(_CORE_DIR, "")
    for module in modules:
        origin = getattr(module, "__file__", None)
        if origin is None:
            continue
        # Some extracted modules are single files directly in _core; others
        # (notably _dafny) are packages with their own subdirectory. Test for
        # containment under _core rather than exact directory equality.
        if not _os.path.abspath(origin).startswith(core_prefix):
            raise ImportError(
                f"agent_host_protocol: module {getattr(module, '__name__', module)!r} "
                f"was loaded from {origin!r}, not from this package's extracted core "
                f"at {_CORE_DIR!r}.\n"
                "Another Dafny-extracted package in this environment has already "
                "claimed that module name. Dafny's Python backend emits flat "
                "top-level module names, so the two cannot coexist in one process. "
                "Install them in separate environments."
            )


_assert_own_core(
    _AhpSkeleton, _Annotations, _Canvas, _Changeset,
    _Chat, _ResourceWatch, _Session, _Terminal, _dafny,
)

#: Root channel - agent/session/terminal registry and client config.
root = _AhpSkeleton
#: Session channel - session lifecycle.
session = _Session
#: Chat channel - turn lifecycle and tool-call state machine.
chat = _Chat
#: Terminal channel - terminal streams.
terminal = _Terminal
#: Canvas channel - canvas surface.
canvas = _Canvas
#: Changeset channel - file changesets.
changeset = _Changeset
#: Annotations channel - source annotations.
annotations = _Annotations
#: ResourceWatch channel - resource watching.
resource_watch = _ResourceWatch

#: The Dafny runtime support module (sequences, maps, bignums, ...).
dafny = _dafny

__version__ = "0.1.0"

CHANNELS = (
    "root",
    "session",
    "chat",
    "terminal",
    "canvas",
    "changeset",
    "annotations",
    "resource_watch",
)

__all__ = (
    "CHANNELS",
    "CORPUS_EXPECTED",
    "CORPUS_TOTAL",
    "check_corpus",
    "dafny",
    "run_corpus",
    "__version__",
    *CHANNELS,
)


#: Expected ``(passed, total)`` for every channel of the embedded corpus.
#:
#: Hard-coded so the denominators cannot drift silently. A channel whose
#: ``RunCorpus`` is missing, or which returns a different total, is a failure
#: rather than a smaller number: ``run_corpus`` raises and ``check_corpus``
#: reports it. Totals sum to :data:`CORPUS_TOTAL`.
CORPUS_EXPECTED: dict[str, int] = {
    "root": 7,
    "resource_watch": 2,
    "canvas": 5,
    "changeset": 15,
    "annotations": 10,
    "terminal": 19,
    "session": 36,
    "chat": 54,
}

#: Total fixtures in the embedded per-action corpus.
CORPUS_TOTAL = sum(CORPUS_EXPECTED.values())  # 148


def run_corpus() -> dict[str, tuple[int, int]]:
    """Run the embedded reducer fixture corpus against the extracted code.

    Returns a mapping of channel name to a ``(passed, total)`` pair.

    Raises ``RuntimeError`` if any channel does not expose ``RunCorpus``.
    A missing runner previously caused that channel to be skipped, which
    silently shrank the reported total; an absent runner is now an error.
    """
    results: dict[str, tuple[int, int]] = {}
    missing: list[str] = []
    for name in CHANNELS:
        module = globals()[name]
        runner = getattr(module.default__, "RunCorpus", None)
        if runner is None:
            missing.append(name)
            continue
        passed, total = runner()
        results[name] = (int(passed), int(total))
    if missing:
        raise RuntimeError(
            "extracted corpus runner missing for channel(s): "
            + ", ".join(missing)
            + ". The shipped extraction is incomplete; refusing to report a "
            "partial corpus result as a pass."
        )
    return results


def check_corpus() -> dict[str, tuple[int, int]]:
    """Run the corpus and assert every fixture passed, against pinned totals.

    This is the installation self-test. It fails if a channel is missing, if
    any fixture fails, or if a channel's fixture count differs from
    :data:`CORPUS_EXPECTED` — so a corpus that quietly got smaller is a
    failure, not a smaller green number.
    """
    results = run_corpus()
    problems: list[str] = []

    for name, expected_total in CORPUS_EXPECTED.items():
        if name not in results:
            problems.append(f"{name}: no result")
            continue
        passed, total = results[name]
        if total != expected_total:
            problems.append(
                f"{name}: expected {expected_total} fixtures, ran {total}"
            )
        if passed != total:
            problems.append(f"{name}: {total - passed} of {total} fixture(s) failed")

    unexpected = set(results) - set(CORPUS_EXPECTED)
    if unexpected:
        problems.append(f"unexpected channel(s): {', '.join(sorted(unexpected))}")

    grand_total = sum(total for _, total in results.values())
    if grand_total != CORPUS_TOTAL:
        problems.append(f"corpus total {grand_total}, expected {CORPUS_TOTAL}")

    if problems:
        raise AssertionError("corpus check failed:\n  " + "\n  ".join(problems))
    return results
