// C ABI over the AHP Terminal channel reducer.
//
// TRUST CHAIN
//   * `Terminal::_default::apply1` and `Terminal::_default::fold` are MACHINE-
//     GENERATED by `dafny translate rs` from the verified Dafny core. Nothing in
//     this file reimplements reducer logic; every state transition below is a
//     call into that generated code.
//   * THIS FILE IS HAND-WRITTEN BINDING GLUE and is NOT verified. Its job is
//     marshalling: C string <-> Dafny Sequence<DafnyChar>, C int64 <-> DafnyInt,
//     and owning/releasing Rc handles across the boundary.
//
// MEMORY CONTRACT
//   * Every `ahp_terminal_*` constructor/transition returns an owned handle the
//     caller must release with `ahp_terminal_free`.
//   * Every `char*` returned is owned by the caller and must be released with
//     `ahp_string_free`.
//   * Transitions never mutate their input handle: the reducer is pure, so the
//     input state remains valid and independently owned after the call.
//
// Copyright (c) Microsoft Corporation
// Copyright (c) 2026 Josh Mouch
// SPDX-License-Identifier: MIT

#![allow(non_snake_case)]

use ::dafny_runtime::{DafnyInt, Sequence, DafnyChar};
use ::std::ffi::{CStr, CString};
use ::std::os::raw::c_char;
use ::std::rc::Rc;

use crate::AhpSkeleton::Option as AhpOption;
use crate::Terminal::{TerminalAction, TerminalState};

/// Opaque handle. `TerminalState` is an `Rc`-managed Dafny datatype; the C side
/// only ever sees a pointer.
pub struct AhpTerminalState {
    inner: Rc<TerminalState>,
}

// ---------------------------------------------------------------- marshalling

/// Borrow a C string as a Dafny string. Returns None on NULL or invalid UTF-8.
unsafe fn to_dafny_str(p: *const c_char) -> Option<Sequence<DafnyChar>> {
    if p.is_null() {
        return None;
    }
    let s = CStr::from_ptr(p).to_str().ok()?;
    Some(::dafny_runtime::string_of(s))
}

/// Convert a Dafny string into a freshly-allocated C string.
fn from_dafny_str(s: &Sequence<DafnyChar>) -> *mut c_char {
    let rust: String = s.to_array().iter().map(|c| c.0).collect();
    match CString::new(rust) {
        Ok(c) => c.into_raw(),
        Err(_) => ::std::ptr::null_mut(),
    }
}

fn handle(inner: Rc<TerminalState>) -> *mut AhpTerminalState {
    Box::into_raw(Box::new(AhpTerminalState { inner }))
}

unsafe fn borrow<'a>(h: *const AhpTerminalState) -> Option<&'a Rc<TerminalState>> {
    if h.is_null() { None } else { Some(&(*h).inner) }
}

/// Apply one action through the VERIFIED reducer.
unsafe fn apply(
    h: *const AhpTerminalState,
    action: Rc<TerminalAction>,
) -> *mut AhpTerminalState {
    match borrow(h) {
        None => ::std::ptr::null_mut(),
        // vvv the verified reducer vvv
        Some(state) => handle(crate::Terminal::_default::apply1(state, &action)),
    }
}

// ------------------------------------------------------------------ lifecycle

/// Initial terminal state (Dafny `Terminal.T0()`).
#[no_mangle]
pub extern "C" fn ahp_terminal_initial() -> *mut AhpTerminalState {
    handle(crate::Terminal::_default::T0())
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_free(h: *mut AhpTerminalState) {
    if !h.is_null() {
        drop(Box::from_raw(h));
    }
}

#[no_mangle]
pub unsafe extern "C" fn ahp_string_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}

// ----------------------------------------------------------------- transitions
// Each returns a NEW state; the input handle is untouched (the reducer is pure).

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_cwd_changed(
    h: *const AhpTerminalState,
    cwd: *const c_char,
) -> *mut AhpTerminalState {
    match to_dafny_str(cwd) {
        None => ::std::ptr::null_mut(),
        Some(cwd) => apply(h, Rc::new(TerminalAction::TCwdChanged { cwd })),
    }
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_title_changed(
    h: *const AhpTerminalState,
    title: *const c_char,
) -> *mut AhpTerminalState {
    match to_dafny_str(title) {
        None => ::std::ptr::null_mut(),
        Some(title) => apply(h, Rc::new(TerminalAction::TTitleChanged { title })),
    }
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_resized(
    h: *const AhpTerminalState,
    cols: i64,
    rows: i64,
) -> *mut AhpTerminalState {
    apply(
        h,
        Rc::new(TerminalAction::TResized {
            cols: DafnyInt::from(cols),
            rows: DafnyInt::from(rows),
        }),
    )
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_exited(
    h: *const AhpTerminalState,
    code: i64,
) -> *mut AhpTerminalState {
    apply(h, Rc::new(TerminalAction::TExited { code: DafnyInt::from(code) }))
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_data(
    h: *const AhpTerminalState,
    data: *const c_char,
) -> *mut AhpTerminalState {
    match to_dafny_str(data) {
        None => ::std::ptr::null_mut(),
        Some(data) => apply(h, Rc::new(TerminalAction::TData { data })),
    }
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_cleared(
    h: *const AhpTerminalState,
) -> *mut AhpTerminalState {
    apply(h, Rc::new(TerminalAction::TCleared {}))
}

/// Fold a batch of `data` actions through the core's proven kernel fold
/// (`Terminal.fold`), rather than looping `apply1` on the C++ side. Proves the
/// higher-order path -- the thing the C++ backend could not express -- works.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_fold_data(
    h: *const AhpTerminalState,
    items: *const *const c_char,
    count: usize,
) -> *mut AhpTerminalState {
    let state = match borrow(h) {
        None => return ::std::ptr::null_mut(),
        Some(s) => s,
    };
    if items.is_null() && count != 0 {
        return ::std::ptr::null_mut();
    }
    let mut actions: Vec<Rc<TerminalAction>> = Vec::with_capacity(count);
    for i in 0..count {
        match to_dafny_str(*items.add(i)) {
            None => return ::std::ptr::null_mut(),
            Some(data) => actions.push(Rc::new(TerminalAction::TData { data })),
        }
    }
    let seq = Sequence::<Rc<TerminalAction>>::from_array_owned(actions);
    // vvv the verified kernel fold vvv
    handle(crate::Terminal::_default::fold(state, &seq))
}

// -------------------------------------------------------------------- readouts

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_title(h: *const AhpTerminalState) -> *mut c_char {
    match borrow(h) {
        None => ::std::ptr::null_mut(),
        Some(s) => from_dafny_str(s.title()),
    }
}

/// Returns NULL when the reducer holds `None` for cwd (distinct from "" ).
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_cwd(h: *const AhpTerminalState) -> *mut c_char {
    match borrow(h) {
        None => ::std::ptr::null_mut(),
        Some(s) => match &**s.cwd() {
            AhpOption::Some { value } => from_dafny_str(value),
            AhpOption::None {} => ::std::ptr::null_mut(),
        },
    }
}

/// 1 = present (value written to `out`), 0 = None.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_exit_code(
    h: *const AhpTerminalState,
    out: *mut i64,
) -> i32 {
    let s = match borrow(h) {
        None => return 0,
        Some(s) => s,
    };
    match &**s.exitCode() {
        AhpOption::Some { value } => {
            if !out.is_null() {
                *out = i64::try_from(value.clone()).unwrap_or(0);
            }
            1
        }
        AhpOption::None {} => 0,
    }
}

/// 1 = present, 0 = None.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_size(
    h: *const AhpTerminalState,
    cols: *mut i64,
    rows: *mut i64,
) -> i32 {
    let s = match borrow(h) {
        None => return 0,
        Some(s) => s,
    };
    match (&**s.cols(), &**s.rows()) {
        (AhpOption::Some { value: c }, AhpOption::Some { value: r }) => {
            if !cols.is_null() {
                *cols = i64::try_from(c.clone()).unwrap_or(0);
            }
            if !rows.is_null() {
                *rows = i64::try_from(r.clone()).unwrap_or(0);
            }
            1
        }
        _ => 0,
    }
}

/// Number of content parts accumulated by the reducer.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_content_len(h: *const AhpTerminalState) -> usize {
    match borrow(h) {
        None => 0,
        Some(s) => s.content().cardinality_usize(),
    }
}

// ------------------------------------------------------------- full corpus
//
// `ClientMain.Main` is the verified core's OWN conformance corpus: it replays
// every channel's fixture set through the reducers and `expect`s a full green
// board. Exposing it lets a C++ caller confirm that this Rust extraction
// reproduces the core's own expectations across all eight channels -- far
// broader coverage than the handful of transitions the C ABI above surfaces.
//
// A failed corpus expectation aborts the process (this crate is built with
// `panic = "abort"`, because unwinding across a C ABI boundary is undefined
// behaviour). So "this function returned at all" IS the pass signal; there is no
// silent-failure path. Prints the corpus board to stdout.
#[no_mangle]
pub extern "C" fn ahp_run_corpus() -> i32 {
    let args: Sequence<Sequence<DafnyChar>> = Sequence::from_array_owned(vec![]);
    crate::ClientMain::_default::Main(&args);
    0
}
