// C ABI over the AHP Terminal channel reducer.
//
// TRUST CHAIN
//   * `Terminal::_default::apply1` and `Terminal::_default::fold` are MACHINE-
//     GENERATED by `dafny translate rs` from the verified Dafny core. Nothing in
//     this file reimplements reducer logic; every state transition below is a
//     call into that generated code.
//   * THIS FILE IS HAND-WRITTEN BINDING GLUE and is NOT verified. Its job is
//     marshalling: C string <-> Dafny Sequence<DafnyChar>, C int64 <-> DafnyInt,
//     and owning/releasing state handles across the boundary.
//
// MEMORY CONTRACT
//   * Every `ahp_terminal_*` constructor/transition returns an owned handle the
//     caller must release with `ahp_terminal_free`.
//   * Every `char*` returned is owned by the caller and must be released with
//     `ahp_string_free`.
//   * Transitions never mutate their input handle: the reducer is pure, so the
//     input state remains valid and independently owned after the call.
//
// HANDLES ARE IDS, NOT POINTERS
//   `AhpTerminalState*` is an opaque token, not a dereferenceable address. Each
//   handle is a monotonically increasing id that indexes a private registry;
//   ids are NEVER reused. A stale handle (use-after-free, double-free) therefore
//   never resolves to a different live state: it is refused. Readouts return
//   NULL and `ahp_terminal_free` is a no-op. Callers must not dereference a
//   handle, and must not synthesize one.
//
// THREAD SAFETY
//   Every entry point below is safe to call concurrently from any thread. The
//   Dafny-extracted core is NOT itself thread-safe -- `dafny translate rs`
//   without `--rust-sync` emits `std::rc::Rc` (a NON-ATOMIC refcount), and
//   `dafny_runtime::Sequence` mutates itself through an `UnsafeCell` when it
//   lazily flattens a concatenation, so even two concurrent READS of one state
//   are a data race. Derived states structurally share subterms with their
//   parents, so the race is reachable from ordinary use of this C ABI.
//
//   Because this crate consumes ALREADY-EXTRACTED Rust, it cannot switch the
//   core to `Arc`; that requires regenerating with `--rust-sync`. Instead this
//   layer takes a process-wide lock around every entry point, so all core
//   values are touched under mutual exclusion, in one total order, with
//   happens-before edges supplied by the mutex. No refcount and no sequence
//   cell is ever touched concurrently.
//
//   The cost is honest and stated in the header: calls into the core are
//   SERIALIZED. This is a correctness-over-throughput choice. The reducers are
//   pure and short; the lock is held only for the duration of one call.
//
// UTF-8 CONTRACT (shared by all three bindings in this repository)
//   Input strings MUST be well-formed UTF-8. Invalid input is REFUSED, never
//   repaired: a function returning a pointer returns NULL. Substituting
//   U+FFFD for invalid bytes would silently merge distinct inputs -- two
//   different identifiers becoming one verified state -- so the binding refuses
//   rather than corrupt the values the proofs reason about.
//
// Copyright (c) Microsoft Corporation
// Copyright (c) 2026 Josh Mouch
// SPDX-License-Identifier: MIT

#![allow(non_snake_case)]

use ::dafny_runtime::{DafnyChar, DafnyInt, Sequence};
use ::std::collections::HashMap;
use ::std::ffi::{CStr, CString};
use ::std::os::raw::c_char;
use ::std::rc::Rc;
use ::std::sync::{LazyLock, Mutex, MutexGuard};

use crate::AhpSkeleton::Option as AhpOption;
use crate::Terminal::{TerminalAction, TerminalState};

/// Opaque handle type. Never instantiated: a `*mut AhpTerminalState` carries a
/// registry id in its address bits and must never be dereferenced by anyone.
pub enum AhpTerminalState {}

/// Largest `count` accepted by `ahp_terminal_fold_data`.
///
/// The length of a C array cannot be checked against the array itself, so a
/// bogus count (classically a `size_t` underflow from `v.size() - 1` on an
/// empty vector) is indistinguishable from a real one. What this bound CAN do
/// is refuse counts that cannot be a real array, before any allocation sized
/// from that count happens. Beyond this bound the call is refused with NULL.
const MAX_FOLD_ITEMS: usize = 1 << 20;

// ------------------------------------------------------------------ registry

/// The live states, keyed by handle id. Ids start at 1 (0 is reserved for the
/// NULL handle) and are never reused, so a stale id can never alias a live one.
struct Registry {
    states: HashMap<u64, Rc<TerminalState>>,
    next: u64,
}

/// SAFETY: `Rc<TerminalState>` is `!Send` because its refcount is non-atomic.
/// This wrapper is only ever reachable through `REGISTRY`, a `Mutex`, and every
/// entry point in this file takes that mutex for the whole duration of its work
/// -- including every clone, drop, read and construction of a core value. All
/// accesses are therefore mutually exclusive and totally ordered, with the
/// happens-before edges the `Rc` refcount needs supplied by the mutex's
/// acquire/release. No core value is ever touched by two threads at once, which
/// is the property `Send` would otherwise be asserting. Nothing hands an `Rc`
/// out past the guard: handles crossing the C boundary are integer ids.
unsafe impl Send for Registry {}

static REGISTRY: LazyLock<Mutex<Registry>> = LazyLock::new(|| {
    Mutex::new(Registry {
        states: HashMap::new(),
        next: 1,
    })
});

/// Enter the core. Held for the whole of every entry point; see THREAD SAFETY.
///
/// The crate is built with `panic = "abort"`, so the mutex can never be
/// poisoned; `into_inner()` on the error path is defensive only.
fn enter() -> MutexGuard<'static, Registry> {
    match REGISTRY.lock() {
        Ok(g) => g,
        Err(poisoned) => poisoned.into_inner(),
    }
}

impl Registry {
    /// Registers a state and returns its handle.
    fn insert(&mut self, state: Rc<TerminalState>) -> *mut AhpTerminalState {
        let id = self.next;
        self.next += 1;
        self.states.insert(id, state);
        id as *mut AhpTerminalState
    }

    /// Resolves a handle, or None when it is NULL, never issued, or released.
    fn get(&self, h: *const AhpTerminalState) -> Option<&Rc<TerminalState>> {
        self.states.get(&(h as u64))
    }

    /// Releases a handle. Returns false when it was not live, which makes
    /// double-free a no-op rather than a corruption.
    fn remove(&mut self, h: *mut AhpTerminalState) -> bool {
        self.states.remove(&(h as u64)).is_some()
    }
}

// ---------------------------------------------------------------- marshalling

/// Borrow a C string as a Dafny string. Returns None on NULL or invalid UTF-8.
/// Invalid UTF-8 is REFUSED, not repaired -- see the UTF-8 CONTRACT above.
unsafe fn to_dafny_str(p: *const c_char) -> Option<Sequence<DafnyChar>> {
    if p.is_null() {
        return None;
    }
    let s = CStr::from_ptr(p).to_str().ok()?;
    Some(::dafny_runtime::string_of(s))
}

/// Convert a Dafny string into a freshly-allocated C string.
fn from_dafny_str(s: &Sequence<DafnyChar>) -> *mut c_char {
    let rust: String = s.to_array().iter().map(|c| c.0).collect();
    match CString::new(rust) {
        Ok(c) => c.into_raw(),
        Err(_) => ::std::ptr::null_mut(),
    }
}

/// Apply one action through the VERIFIED reducer, under the registry lock.
fn apply(
    reg: &mut Registry,
    h: *const AhpTerminalState,
    action: Rc<TerminalAction>,
) -> *mut AhpTerminalState {
    let next = match reg.get(h) {
        None => return ::std::ptr::null_mut(),
        // vvv the verified reducer vvv
        Some(state) => crate::Terminal::_default::apply1(state, &action),
    };
    reg.insert(next)
}

/// Apply an action whose only argument is a string, refusing NULL/non-UTF-8.
unsafe fn apply_str(
    h: *const AhpTerminalState,
    text: *const c_char,
    build: fn(Sequence<DafnyChar>) -> TerminalAction,
) -> *mut AhpTerminalState {
    let mut reg = enter();
    match to_dafny_str(text) {
        None => ::std::ptr::null_mut(),
        Some(text) => apply(&mut reg, h, Rc::new(build(text))),
    }
}

// ------------------------------------------------------------------ lifecycle

/// Initial terminal state (Dafny `Terminal.T0()`).
#[no_mangle]
pub extern "C" fn ahp_terminal_initial() -> *mut AhpTerminalState {
    let mut reg = enter();
    let state = crate::Terminal::_default::T0();
    reg.insert(state)
}

/// Releases a handle. Releasing a handle that was never issued, or that was
/// already released, is a no-op: handle ids are never reused, so a stale id
/// cannot name a live state.
#[no_mangle]
pub extern "C" fn ahp_terminal_free(h: *mut AhpTerminalState) {
    let mut reg = enter();
    reg.remove(h);
}

/// 1 when the handle names a live state, 0 otherwise. Lets a C caller check a
/// handle instead of guessing -- there is no other way to tell from C.
#[no_mangle]
pub extern "C" fn ahp_terminal_valid(h: *const AhpTerminalState) -> i32 {
    let reg = enter();
    if reg.get(h).is_some() {
        1
    } else {
        0
    }
}

/// Releases a string returned by this library. Strings are plain owned
/// allocations that hold no core value, so this needs no lock.
#[no_mangle]
pub unsafe extern "C" fn ahp_string_free(p: *mut c_char) {
    if !p.is_null() {
        drop(CString::from_raw(p));
    }
}

// ----------------------------------------------------------------- transitions
// Each returns a NEW state; the input handle is untouched (the reducer is pure).

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_cwd_changed(
    h: *const AhpTerminalState,
    cwd: *const c_char,
) -> *mut AhpTerminalState {
    apply_str(h, cwd, |cwd| TerminalAction::TCwdChanged { cwd })
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_title_changed(
    h: *const AhpTerminalState,
    title: *const c_char,
) -> *mut AhpTerminalState {
    apply_str(h, title, |title| TerminalAction::TTitleChanged { title })
}

#[no_mangle]
pub extern "C" fn ahp_terminal_resized(
    h: *const AhpTerminalState,
    cols: i64,
    rows: i64,
) -> *mut AhpTerminalState {
    let mut reg = enter();
    apply(
        &mut reg,
        h,
        Rc::new(TerminalAction::TResized {
            cols: DafnyInt::from(cols),
            rows: DafnyInt::from(rows),
        }),
    )
}

#[no_mangle]
pub extern "C" fn ahp_terminal_exited(
    h: *const AhpTerminalState,
    code: i64,
) -> *mut AhpTerminalState {
    let mut reg = enter();
    apply(
        &mut reg,
        h,
        Rc::new(TerminalAction::TExited {
            code: DafnyInt::from(code),
        }),
    )
}

#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_data(
    h: *const AhpTerminalState,
    data: *const c_char,
) -> *mut AhpTerminalState {
    apply_str(h, data, |data| TerminalAction::TData { data })
}

#[no_mangle]
pub extern "C" fn ahp_terminal_cleared(h: *const AhpTerminalState) -> *mut AhpTerminalState {
    let mut reg = enter();
    apply(&mut reg, h, Rc::new(TerminalAction::TCleared {}))
}

/// Fold a batch of `data` actions through the core's proven kernel fold
/// (`Terminal.fold`), rather than looping `apply1` on the C++ side. Proves the
/// higher-order path -- the thing the C++ backend could not express -- works.
///
/// Refuses (NULL) a NULL handle, a NULL `items` with a non-zero `count`, a
/// `count` above `MAX_FOLD_ITEMS`, or any element that is NULL or not UTF-8.
/// The bound is checked BEFORE any allocation is sized from `count`.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_fold_data(
    h: *const AhpTerminalState,
    items: *const *const c_char,
    count: usize,
) -> *mut AhpTerminalState {
    if count > MAX_FOLD_ITEMS {
        return ::std::ptr::null_mut();
    }
    if items.is_null() && count != 0 {
        return ::std::ptr::null_mut();
    }
    let mut reg = enter();
    if reg.get(h).is_none() {
        return ::std::ptr::null_mut();
    }
    // Grown as elements are validated, never sized from an untrusted `count`.
    let mut actions: Vec<Rc<TerminalAction>> = Vec::new();
    for i in 0..count {
        match to_dafny_str(*items.add(i)) {
            None => return ::std::ptr::null_mut(),
            Some(data) => actions.push(Rc::new(TerminalAction::TData { data })),
        }
    }
    let seq = Sequence::<Rc<TerminalAction>>::from_array_owned(actions);
    let state = match reg.get(h) {
        None => return ::std::ptr::null_mut(),
        // vvv the verified kernel fold vvv
        Some(state) => crate::Terminal::_default::fold(state, &seq),
    };
    reg.insert(state)
}

// -------------------------------------------------------------------- readouts

#[no_mangle]
pub extern "C" fn ahp_terminal_title(h: *const AhpTerminalState) -> *mut c_char {
    let reg = enter();
    match reg.get(h) {
        None => ::std::ptr::null_mut(),
        Some(s) => from_dafny_str(s.title()),
    }
}

/// Returns NULL when the reducer holds `None` for cwd (distinct from "" ).
#[no_mangle]
pub extern "C" fn ahp_terminal_cwd(h: *const AhpTerminalState) -> *mut c_char {
    let reg = enter();
    match reg.get(h) {
        None => ::std::ptr::null_mut(),
        Some(s) => match &**s.cwd() {
            AhpOption::Some { value } => from_dafny_str(value),
            AhpOption::None {} => ::std::ptr::null_mut(),
        },
    }
}

/// 1 = present (value written to `out`), 0 = None or invalid handle.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_exit_code(
    h: *const AhpTerminalState,
    out: *mut i64,
) -> i32 {
    let reg = enter();
    let s = match reg.get(h) {
        None => return 0,
        Some(s) => s,
    };
    match &**s.exitCode() {
        AhpOption::Some { value } => {
            if !out.is_null() {
                *out = i64::try_from(value.clone()).unwrap_or(0);
            }
            1
        }
        AhpOption::None {} => 0,
    }
}

/// 1 = present, 0 = None or invalid handle.
#[no_mangle]
pub unsafe extern "C" fn ahp_terminal_size(
    h: *const AhpTerminalState,
    cols: *mut i64,
    rows: *mut i64,
) -> i32 {
    let reg = enter();
    let s = match reg.get(h) {
        None => return 0,
        Some(s) => s,
    };
    match (&**s.cols(), &**s.rows()) {
        (AhpOption::Some { value: c }, AhpOption::Some { value: r }) => {
            if !cols.is_null() {
                *cols = i64::try_from(c.clone()).unwrap_or(0);
            }
            if !rows.is_null() {
                *rows = i64::try_from(r.clone()).unwrap_or(0);
            }
            1
        }
        _ => 0,
    }
}

/// Number of content parts accumulated by the reducer. 0 on an invalid handle.
#[no_mangle]
pub extern "C" fn ahp_terminal_content_len(h: *const AhpTerminalState) -> usize {
    let reg = enter();
    match reg.get(h) {
        None => 0,
        Some(s) => s.content().cardinality_usize(),
    }
}

// ------------------------------------------------------------- full corpus
//
// `ClientMain.Main` is the verified core's OWN conformance corpus: it replays
// every channel's fixture set through the reducers and `expect`s a full green
// board. Exposing it lets a C++ caller confirm that this Rust extraction
// reproduces the core's own expectations across all eight channels -- far
// broader coverage than the handful of transitions the C ABI above surfaces.
//
// A failed corpus expectation aborts the process (this crate is built with
// `panic = "abort"`, because unwinding across a C ABI boundary is undefined
// behaviour). So "this function returned at all" IS the pass signal; there is no
// silent-failure path. Prints the corpus board to stdout.
#[no_mangle]
pub extern "C" fn ahp_run_corpus() -> i32 {
    // Held like every other entry point: the corpus builds and reads core
    // values, so it must not run beside another thread doing the same.
    let _reg = enter();
    let args: Sequence<Sequence<DafnyChar>> = Sequence::from_array_owned(vec![]);
    crate::ClientMain::_default::Main(&args);
    0
}
