// C ABI over the formally-verified AHP core.
//
// `ahpcore.rs` is machine-generated by `dafny translate rs` from the verified
// Dafny core; it is included at the crate root because the Dafny Rust backend
// emits absolute `crate::<Module>::...` paths.
//
// Copyright (c) Microsoft Corporation
// Copyright (c) 2026 Josh Mouch
// SPDX-License-Identifier: MIT
#![allow(warnings, unconditional_panic)]
#![allow(nonstandard_style)]

pub mod _dafny_externs;

include!("ahpcore.rs");

pub mod ffi;
