/*
 * ahp_verified.h — public C/C++ surface for the formally-verified AHP core.
 *
 * This is the header applications should include. It declares the C ABI
 * exported by libahpverified.a, plus the named constants those functions
 * accept and return.
 *
 * Relationship to libahpverified.h
 * --------------------------------
 *   libahpverified.h is generated by cgo from bridge/ahp_bridge.go and is
 *   shipped alongside this header as the raw machine-generated record of the
 *   ABI. It is not const-correct — cgo renders every `*C.char` parameter as
 *   `char*`, which C++ will not bind a string literal to. The declarations
 *   below are the same symbols with input pointers marked const. Under C
 *   linkage the two spellings resolve to identical symbols, so linking is
 *   unaffected. scripts/regenerate.sh verifies after every build that every
 *   symbol declared here is present in the generated header, so the two
 *   cannot silently drift apart.
 *
 * Memory ownership
 * ----------------
 *   - Every char* returned by this library is heap-allocated; release it with
 *     ahp_string_free(). A NULL return means "absent" (a specification-level
 *     Option that is None) or a refusal, per the function's documentation.
 *   - Every uintptr_t Canvas handle must be released exactly once with
 *     ahp_canvas_release(). The reducers are pure: applying an action neither
 *     invalidates nor modifies the input handle, it returns a new one.
 *
 * Threading
 * ---------
 *   The embedded Go runtime initializes on first call and is safe to call
 *   from multiple threads. The verified reducers are pure functions.
 *
 * Copyright (c) Microsoft Corporation
 * Copyright (c) 2026 Josh Mouch
 * SPDX-License-Identifier: MIT
 */

#ifndef AHP_VERIFIED_H
#define AHP_VERIFIED_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * ReduceOutcome, as declared by the specification:
 *     datatype ReduceOutcome = Applied | NoOp | OutOfScope
 * Reported through the outOutcome parameter of the ahp_canvas_apply_* calls.
 */
#define AHP_OUTCOME_APPLIED      0
#define AHP_OUTCOME_NOOP         1
#define AHP_OUTCOME_OUT_OF_SCOPE 2

/*
 * CanvasAvailability, as declared by the specification:
 *     datatype CanvasAvailability = Ready | Stale
 * Returned by ahp_canvas_availability, and accepted by the availability
 * parameter of ahp_canvas_apply_updated. Passing AHP_AVAILABILITY_UNCHANGED
 * there leaves the field alone — the specification's Option None case.
 */
#define AHP_AVAILABILITY_READY     0
#define AHP_AVAILABILITY_STALE     1
#define AHP_AVAILABILITY_UNCHANGED (-1)

/* ── general ─────────────────────────────────────────────────────────────── */

/*
 * Version of THIS binding layer's C ABI. It is not a protocol version: it
 * changes when the C surface changes, and says nothing about the verified
 * core. Release with ahp_string_free.
 */
extern char* ahp_abi_version(void);

/* Releases any char* returned by this library. NULL is accepted. */
extern void ahp_string_free(char* s);

/*
 * Runs the conformance corpus embedded in the verified Session module and
 * reports how many of its modeled cases the extracted reducers reproduce.
 * Writes the pass count and the modeled-case count through the out
 * parameters, either of which may be NULL. Returns 1 when every modeled case
 * passed, 0 otherwise.
 */
extern int ahp_run_corpus(int64_t* outPassed, int64_t* outModeled);

/* ── verified codec and command identity ─────────────────────────────────── */

/*
 * Parses JSON text with the verified parser and re-serializes it with the
 * verified stringifier, yielding the core's canonical spelling of the value.
 * Returns NULL when the text is not accepted by the verified parser. Release
 * a non-NULL result with ahp_string_free.
 */
extern char* ahp_json_canonicalize(const char* text);

/*
 * Computes the verified command-identity digest over `length` bytes at
 * `data`, in the core's "sha256:<hex>" spelling. Release with
 * ahp_string_free.
 */
extern char* ahp_sha256_digest(const char* data, int length);

/* ── Canvas channel reducer ──────────────────────────────────────────────── */

/*
 * Builds a fresh CanvasState with the given identifiers, no title, activity,
 * content URI or input, and Ready availability. Returns an opaque handle the
 * caller releases with ahp_canvas_release.
 */
extern uintptr_t ahp_canvas_new(const char* canvasID, const char* providerID);

/*
 * Applies the Canvas `Updated` action through the verified reducer
 * Canvas.ApplyToCanvas. Each of title, activity and contentURI may be NULL to
 * leave that field untouched; availability takes AHP_AVAILABILITY_READY,
 * AHP_AVAILABILITY_STALE or AHP_AVAILABILITY_UNCHANGED. Returns a new handle;
 * the input handle stays valid and unmodified. When outOutcome is non-NULL it
 * receives the reducer's AHP_OUTCOME_* verdict.
 */
extern uintptr_t ahp_canvas_apply_updated(uintptr_t handle,
                                          const char* title,
                                          const char* activity,
                                          const char* contentURI,
                                          int availability,
                                          int64_t now,
                                          int* outOutcome);

/*
 * Applies the Canvas `CloseRequested` action through the verified reducer.
 * The specification defines it as state-preserving, so the returned state
 * equals the input and the outcome is AHP_OUTCOME_NOOP — that verdict comes
 * from the verified reducer, not from the binding.
 */
extern uintptr_t ahp_canvas_apply_close_requested(uintptr_t handle,
                                                  int64_t now,
                                                  int* outOutcome);

/* Returns the canvasId field. Release with ahp_string_free. */
extern char* ahp_canvas_id(uintptr_t handle);

/* Returns the providerId field. Release with ahp_string_free. */
extern char* ahp_canvas_provider_id(uintptr_t handle);

/* Returns the title, or NULL when None. Release non-NULL with ahp_string_free. */
extern char* ahp_canvas_title(uintptr_t handle);

/* Returns the activity, or NULL when None. Release non-NULL with ahp_string_free. */
extern char* ahp_canvas_activity(uintptr_t handle);

/* Returns the contentUri, or NULL when None. Release non-NULL with ahp_string_free. */
extern char* ahp_canvas_content_uri(uintptr_t handle);

/* Returns AHP_AVAILABILITY_READY or AHP_AVAILABILITY_STALE. */
extern int ahp_canvas_availability(uintptr_t handle);

/*
 * Structural equality over two Canvas states, decided by the extracted
 * datatype's own equality. Returns 1 when equal, 0 otherwise.
 */
extern int ahp_canvas_equals(uintptr_t a, uintptr_t b);

/*
 * Releases a Canvas handle. Every handle returned by ahp_canvas_new or an
 * ahp_canvas_apply_* call must be released exactly once.
 */
extern void ahp_canvas_release(uintptr_t handle);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* AHP_VERIFIED_H */
