/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/joshmouch/ahp-verified/cpp-via-go/bridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 20 "ahp_bridge.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* ahp_abi_version(void);
extern void ahp_string_free(char* s);
extern int ahp_run_corpus(int64_t* outPassed, int64_t* outModeled);
extern char* ahp_json_canonicalize(char* text);
extern char* ahp_sha256_digest(char* data, int length);
extern uintptr_t ahp_canvas_new(char* canvasID, char* providerID);
extern uintptr_t ahp_canvas_apply_updated(uintptr_t handle, char* title, char* activity, char* contentURI, int availability, int64_t now, int* outOutcome);
extern uintptr_t ahp_canvas_apply_close_requested(uintptr_t handle, int64_t now, int* outOutcome);
extern char* ahp_canvas_id(uintptr_t handle);
extern char* ahp_canvas_provider_id(uintptr_t handle);
extern char* ahp_canvas_title(uintptr_t handle);
extern char* ahp_canvas_activity(uintptr_t handle);
extern char* ahp_canvas_content_uri(uintptr_t handle);
extern int ahp_canvas_availability(uintptr_t handle);
extern int ahp_canvas_equals(uintptr_t a, uintptr_t b);
extern void ahp_canvas_release(uintptr_t handle);

#ifdef __cplusplus
}
#endif
